---

# Ref: https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name:  Build and push action container image to repository

on:
    push:
        tags:
            - v[0-9]+.[0-9]+

env:
    _REG: quay.io
    # N/B: Will be of the form "<org>/<user>"
    _IMG: ${{ github.repository }}

jobs:
    push:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@master

            - name: Set environment variables
              env:
                  _REG: quay.io
              run: |
                  _TAG="$(basename $GITHUB_REF)"
                  # Assert always running against a tagged commit
                  echo "$_TAG" | egrep -q '^v[0-9]+.[0-9]+'
                  # Evaluate values here so they're static upon load
                  cat << EOF > .env
                  set -eaxuo pipefail
                  ENV_IMG="${_IMG}"
                  ENV_TAG="${_TAG}"
                  ENV_FQIN="${_REG}/${_IMG}:${_TAG}"
                  ENV_IMG_FILENAME="$(basename ${_IMG})-${_TAG}.tar"
                  EOF

            - name: Verify action YAML references matching image tag
              run: |
                  source .env
                  egrep -m 1 -q "^\s+image:\s+['\"]?docker://${ENV_FQIN}['\"]?$" action.yml

            - name: Verify README.md example references action tag
              run: |
                  source .env
                  egrep -m 1 -q "^uses:\s+['\"]?${ENV_IMG}@${ENV_TAG}['\"]?$" README.md

            - name: Build container image
              run: |
                  source .env
                  docker build -t "${ENV_FQIN}" .

            - name: Save image to tar file
              run: |
                  source .env
                  mkdir -p artifacts
                  docker save "${ENV_FQIN}" > "artifacts/${ENV_IMG_FILENAME}"

            - name: Upload artifacts
              uses: actions/upload-artifact@master
              with:
                  name: artifacts
                  path: artifacts

            - name: Push image to registry
              env:
                  # Ref: https://github.com/cevich/makecontaineraction/settings/secrets
                  _BOT_CREDENTIALS: ${{ secrets.bot_credentials }}
              run: |
                  source .env
                  mkdir -p "$HOME/.docker"
                  trap "rm -vrf $HOME/.docker" EXIT
                  set +x
                  echo "$_BOT_CREDENTIALS" |& base64 --decode &> "$HOME/.docker/config.json"
                  docker push "${ENV_FQIN}"
